### ISSUE TITLE
Ready for review

### ISSUE THREAD

**Issue by srikbe** [srikbe/education-front-end#49]
Front end repo: https://github.com/srikbe/education-front-end
Back end repo: https://github.com/srikbe/education-back-end
Trello: https://trello.com/b/dIHIqecK/educationteam
User stories and notes on data: https://github.com/srikbe/education-front-end/blob/master/README.md
Scrum notes: https://github.com/srikbe/education-front-end/blob/master/scrumnotes.txt
Sprint: https://github.com/srikbe/education-front-end/blob/master/retrospective.txt
Website: https://srikbe.github.io/education-front-end/

**Comment by dmil** [comment]
Thanks! Project has been reviewed and feedback has been sent to you via email! I'm closing this github issue.
